Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"

  # https://developer.hashicorp.com/vagrant/docs/networking/basic_usage
  config.vm.hostname = "p3"
  config.vm.network "private_network", ip: "192.168.56.110"

  # https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/configuration
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--name", "p3"]
    v.memory = 1024
    v.cpus = 1
  end

  # https://developer.hashicorp.com/vagrant/docs/provisioning/shell
  config.vm.provision "shell", path: "scripts/install-docker.sh"
  config.vm.provision "shell", path: "scripts/install-k3d.sh"
  config.vm.provision "shell", path: "scripts/install-argocd.sh"
  config.vm.provision "shell", path: "scripts/deploy-app.sh"
end